### ISSUE TITLE
Show update notification immediately after start up

### ISSUE THREAD

**Issue by jelhan** [topaxi/ember-service-worker-update-notify#19]
If user start the app with an outdated version, he won't see an update notification before `pollingInterval` is over. This seems to be intended: https://github.com/topaxi/ember-service-worker-update-notify/blob/341371d393a62900fc655bf6bc4d07a5b03b0bc4/addon/components/service-worker-update-notify.js#L16-L19

This doesn't fit my use case well. I want to show the user a notification as soon as possible. This is also what I'm used to from other apps (e.g. CodeSandbox). It would be nice, if we could configure the initial delay.

A non-breaking change would be introducing a `initialDelay` configuration option that defaults to `pollingInterval`. But I'm not sure if the current behavior is a reasonable default. I would image that most applications want to inform the user about an update being available as soon as possible.

**Comment by NullVoxPopuli** [comment]
I also don't remember what the reason was. :)

I can do a PR after some experimenting and post my findings.

**Comment by jelhan** [comment]
Alternatively or as an addition a service could be provided that allows to check if there is an update. This would also support use cases like forcing an update on boot up.

**Comment by simonihmig** [comment]
> This would also support use cases like forcing an update on boot up.

I just stumbled upon this, and this is the exactly the use case I was trying to solve. I will try to create a PR...

**Comment by NullVoxPopuli** [comment]
@simonihmig there is some in-progress work here: https://github.com/topaxi/ember-service-worker-update-notify/pull/18 if you want to continue it

**Comment by NullVoxPopuli** [comment]
or maybe that's different. o.o

**Comment by simonihmig** [comment]
Thanks for mentioning @NullVoxPopuli, I would have missed that. But I was thinking about the following:
* extracting the sw interaction and polling into a service (as @jelhan has already suggested)
* that service could emit an event on update 
* the existing component could listen for that event, so the component use case continues to work without breaking changes
* users could listen for that event on their own, and implement some own imperative actions, like forcing reload, or triggering a flash message (through another service) or whatever
* part of that would probably also be to not delay the initial update check, if that has not been covered elsewhere already.

Does that make sense?

Either way your existing work looks very promising, especially the infrastructure to allow testing. So I would love to have that available for any further work. So what's the state of this? At least #16 seems good to merge AFAICT?

**Comment by NullVoxPopuli** [comment]
> Does that make sense?

it does! and I like the goal of flexibility!

I have a concern though:

> that service could emit an event on update

do we want to formally use events? or just register callbacks? since eventing is trying to get deprecated over here: https://github.com/emberjs/rfcs/pull/528

> At least #16 seems good to merge AFAICT?

I think so. I just didn't want to merge my own PR. was mostly waiting for @topaxi , but I guess the PR was approved.

**Comment by simonihmig** [comment]
> do we want to formally use events? 

I have it basically working now with events, but thought about the same. Not sure though if that RFC is really going to be accepted though. I believe there are valid use cases for eventing. 

We could expose a promise on the service that resolves when an update is found. However that would only work when you are only interested in a one-time notification. (which is currently the case, due to https://github.com/topaxi/ember-service-worker-update-notify/blob/master/addon/components/service-worker-update-notify.js#L79)

> or just register callbacks

What exactly do you mean? Sounds a bit like a re-implementation of events?

**Comment by NullVoxPopuli** [comment]
>  Not sure though if that RFC is really going to be accepted though

yeah, personally, I'm on the fence. I'd like to see more alternatives and analysis about what we gain from removing events.

> What exactly do you mean? Sounds a bit like a re-implementation of events?

Maybe?

something like this:

from the consuming side:
```ts
constructor(...args) {
  super(...args);
  this.whateverTheServiceIsCalled.onUpdate(() => { function for doing stuff });
}
```
in the service:
```ts
  @tracked updateHooks = [];

  onUpdate(callback) {
    this.updateHooks = [...this.updateHooks, callback];
  }
   
  _receivedUpdateNotificationFromServiceWorker() {
    updateHooks.forEach(callback => callback());
  }
```
or something like that? idk

**Comment by simonihmig** [comment]
> something like this:

Yeah, but that is basically a reimplementation of events in user-land, isn't it? 😀

Like `this.whateverTheServiceIsCalled.onUpdate(() => {})` is equivalent to `this.whateverTheServiceIsCalled.on('update', () => {})`. 
And `updateHooks.forEach(callback => callback())` is `this.trigger('update')`. 

No change architecture-wise IMO, still sync callbacks triggered by some kind of event. I see a point to omit events when it is possible to rewrite the observer-ish imperative callbacks into a more declarative architecture, where the work to react to changes is offloaded to the framework - especially tracked props (see https://github.com/emberjs/rfcs/pull/528#issuecomment-525058391). But that works AFAIK only when some of that (derived) state is consumed in a template, not when you need to call something imperatively, like e.g. `window.location.reload()` in our use case.

**Comment by NullVoxPopuli** [comment]
>  I see a point to omit events when it is possible to rewrite the observer-ish imperative callbacks into a more declarative architecture, where the work to react to changes is offloaded to the framework 

truth -- I guess we'll update to something without events when we _have_ to :man_shrugging: :)
