### ISSUE TITLE
Remove default component content

### ISSUE THREAD

**Issue by simonihmig** [topaxi/ember-service-worker-update-notify#21]
I would assume that virtually no one ever uses the default content that comes from the component here: https://github.com/topaxi/ember-service-worker-update-notify/blob/master/addon/templates/components/service-worker-update-notify.hbs#L5, for either using custom markup, different wording, i18n or whatelse. So instead of shipping those few extra bytes of IMO useless template code (admittedly not much), I would suggest to remove that and only support the current block mode.

This could be done as part of the major release required for #20 anyway. 
Thoughts? @topaxi @NullVoxPopuli

**Comment by NullVoxPopuli** [comment]
> I would assume that virtually no one ever uses the default content

that's probably true.

I'm a fan of that going away as part of the upcoming major release. My hunch is that it was used to make testing easier -- but the content should probably go into the integration test itself

**Comment by topaxi** [comment]
I don't mind removing the default content, I initially put it there to at least have _something_.
