### ISSUE TITLE
Polling prevents settledness in tests

### ISSUE THREAD

**Issue by simonihmig** [topaxi/ember-service-worker-update-notify#22]
The polling task prevents `await settled()` (or any other related test helpers waiting for settledness) to occur. Not only in the tests of this addon (see https://github.com/topaxi/ember-service-worker-update-notify/blob/master/tests/acceptance/usage-test.js#L45-L47), but also in any app that uses the addon it seems.

As the current test infrastructure does not really test the polling part, but short-cuts the update detection (see https://github.com/topaxi/ember-service-worker-update-notify/pull/20#discussion_r339228306), I think we could just move the `Ember.isTesting` guard before the polling task, not not perform it at all in tests.

Will come up with a PR, that we can discuss, after #20 is merged.

**Comment by NullVoxPopuli** [comment]
awesome! thanks for digging in to this!
