### ISSUE TITLE
A note on testing

### ISSUE THREAD

**Issue by NullVoxPopuli** [topaxi/ember-service-worker-update-notify#5]
with the latest version of esw-update-notify,
you need to not check for updates in acceptance tests.

![image](https://user-images.githubusercontent.com/199018/50404695-c4c18e80-0778-11e9-9fcc-49eed9419eec.png)

because all your tests will be delayed by the polling interval.
Not sure what could be a better solution atm.

**Comment by jrjohnson** [comment]
@NullVoxPopuli an example of an addon integrating polling with testing: https://github.com/sethwebster/ember-cli-new-version/blob/master/addon/components/new-version-notifier/component.js some of which should be integrated here to avoid this issue.

**Comment by NullVoxPopuli** [comment]
I have a plan for real testing!

 - Hook up https://github.com/bendemboski/ember-concurrency-test-waiter to the tasks
 - Extract the service-worker update check to a function
 - Allow the service-worker-update check to be overridden

That would allow us to test this thing in our apps.
Apps should really only be concerned with presence and visual testing though.

**Comment by NullVoxPopuli** [comment]
Resolved via: https://github.com/topaxi/ember-service-worker-update-notify#testing-in-your-app
